version: 1.0.0-rc-1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    powershell .\build.ps1 -Target Default -Verbosity diagnostic
artifacts:
- path: ./Build/nuget/*.nupkg
  name: NuGet
deploy:
  provider: NuGet
  api_key:
    secure: 9rgtIYN6gFA/4oiXym4jAfHtPPBoKNzT7iC+aLmezbLmId7IY9+mueyw9v53C2sb
  skip_symbols: false
  on:
    appveyor_repo_tag: true